Add exemplars for native histograms
prometheus/client_golang pull request #1686
Opened 2024-11-17 19:31 UTC by shivanthzen

2025-01-14 14:56 UTC, shivanthzen commented
@ArthurSens @beorn7 Part-2 for [native histogram support](https://github.com/prometheus/client_golang/issues/1617)

2025-01-21 13:29 UTC, beorn7 commented
This has been on my review list for a while. It's just hard to catch up through all my backlog… :face_exhaling:

2025-01-21 22:00 UTC, beorn7 requested changes
I think this implements the intended idea. Thank you very much. However, I think we should also be able to handle a histogram with both native and classic buckets (even though we have no `MustNewConst...` constructor for it, but people could create it on their own using `dto` primitives). And we need to test that. See comments.

2025-01-21 22:00 UTC, beorn7 commented on prometheus/metric.go
> +				continue
If a classic and a native histogram is exposed at the same time (for the scraper to pick), we should have the exemplars on both. Maybe the following works for that:

```suggestion
				if len(pb.Histogram.Bucket) == 0 {
					// Don't proceed to classic buckets if there are none.
					continue
				}
```

We do have to check if there are already buckets defined, because otherwise there will be an Inf bucket created just for the histograms.

2025-01-21 22:00 UTC, beorn7 commented on prometheus/metric_test.go
> +			{Value: proto.Float64(2000.0), Timestamp: timestamppb.New(time.Date(2009, 11, 17, 20, 34, 58, 3243244, time.UTC))},
We should also test the following cases:

- More than one exemplar.
- An exemplar without timestamp (to verify that a timestamp is added automatically then, because exemplars without timestamps are not allowed for native histograms).
- A histogram with both classic and native buckets. (I believe for that you might have to create an ad-hoc implementation of `Metric` that spits out a custom-made `dto.Metric`.)

2025-01-21 22:00 UTC, beorn7 commented on prometheus/metric.go
> +// Note that for a nativeHistogram, all valid exemplars are injected.
```suggestion
// For a Native Histogram, all valid exemplars are injected.
```

2025-02-06 11:49 UTC, beorn7 commented
@shivanthzen let us know when it is ready for the next round of review.

2025-04-15 22:58 UTC, beorn7 requested changes
Thank you. I have just a naming nit and also just discovered that we need one small actual code change after all.

2025-04-15 22:58 UTC, beorn7 commented on prometheus/metric_test.go
> +func NewDummyConstNativeHistogram(
Let's not export this, so that nobody will use this for real. Also, how about a more descriptive name like "newNativeHistogramWithClassicBuckets"? And finally, end a sentence with a period. :)

```suggestion
// newNativeHistogramWithClassicBuckets returns a Metric representing
// a native histogram that also has classic buckets. This is for testing purposes.
func newNativeHistogramWithClassicBuckets(
```

2025-04-15 22:58 UTC, beorn7 commented on prometheus/metric.go
> +				if *pb.Histogram.Schema > math.MinInt32 && e.GetTimestamp() != nil {
While we use `math.MinInt32` as a schema within the `histogram` struct to mark the absence of sparse buckets, we do not use the same marker in the protobuf. In the protobuf, we know it represents a native histogram if the zero threshold or the zero count or the number of negative spans or the number of positive spans are not zero. (If need be, we add a no-op span.)

So what we have to check is something like the following:
```Go
h := pb.Histogram
if (*h.ZeroThreshold != 0 || *h.ZeroCount != 0 || len(h.PositiveSpan) != 0 || len(h.NegativeSpan) != 0) && e.GetTimestamp() != nil {
```

2025-04-22 08:07 UTC, shivanthzen commented
@beorn7

2025-04-29 10:27 UTC, beorn7 requested changes
Sorry for the review delay.

A small improvement, see comment.

2025-04-30 21:46 UTC, beorn7 requested changes
Could you also resolve the merge conflicts?

2025-04-30 21:46 UTC, beorn7 commented on prometheus/metric.go
> +				(h.ZeroCount != nil && *h.ZeroCount != 0) || len(h.PositiveSpan) != 0 ||
As said, the same trick works here:

```suggestion
				(h.GetZeroCount() != 0) || len(h.PositiveSpan) != 0 ||
```

With this in, you should probably rearrange the line breaks so the grouping makes more sense.

2025-05-06 21:43 UTC, beorn7 approved these changes
Looks good now. Thank you.

2025-05-06 21:47 UTC, merged