add the NewPidFileFn to helper
prometheus/client_golang pull request #804
Opened 2020-10-10 08:45 UTC by sbookworm

for the enhancement: https://github.com/prometheus/client_golang/issues/760

2020-10-12 13:00 UTC, beorn7 requested changes
Thank you for your contribution. It looks good in general. Just minor comments below.

Another thing is the file naming. `helper.go` suggest we will put more helper function in there later. I would either call the file `pid_file_helper.go` (and the test file accordingly), or perhaps even better, just add it to `process_collector.go`, because it's not that much new code, and it is closely tied to the code in `process_collector.go`.

2020-10-20 04:29 UTC, sbookworm commented on prometheus/helper_test.go
> +	defer cleanMockPidFile(mockPidFilePath)
good idea :+1:

2020-10-20 12:18 UTC, sbookworm commented
@beorn7  sorry for using the force option when submitting the changes.
There is only one latest commit now :(  please help to review, thanks

2020-10-20 16:13 UTC, beorn7 requested changes
Code looks good now. But you still have it in files called `helper.go` and `helper_test.go`, which suggests those are files for helper code. But there are no plans right now to add more "helper" code to them. My suggestion is to move the code from `helper.go` to `process_collector.go` and the code from `helper_test.go` to `process_collector_test.go`.

2020-10-20 16:13 UTC, beorn7 commented
> sorry for using the force option when submitting the changes

That's fine for your own branch if it is unlikely that those changes are used somewhere else already.

2020-10-22 17:22 UTC, beorn7 requested changes
Thank you. Just one final thing to do.

2020-10-22 17:22 UTC, beorn7 commented on prometheus/process_collector_test.go
> +// TestNewPidFileFn ...
Final nit: Test functions don't require a doc comment. If you want to provide a meaningful doc comment, go for it. But this one is not meaningful. I'd just delete this line.

2020-10-23 09:55 UTC, beorn7 approved these changes
Thank you.

2020-10-23 09:55 UTC, merged