Adding extension testutils.ToInt()
prometheus/client_golang pull request #893
Opened 2021-07-22 08:46 UTC by kuritka

@bwplotka, @kakkoyun

During testing I need to read metrics which are very often (in our case mostly) integer values.
Prometheus offers only the `testutils.ToFloat64` function, so all results need to be continuously re-typed into integers.
This PR only extends the ToFloat functionality by adding the ToInt function.

Signed-off-by: kuritka <kuritka@gmail.com>

2021-07-22 09:22 UTC, kuritka commented
@bwplotka, @kakkoyun , seems circleci is pending. Should I do some additional steps ? 
thx

2021-07-24 09:29 UTC, bwplotka requested changes
Hi, thanks for your effort! But really it's just one line function - to me it's too shallow to have a dedicated function for this. Anyone can just do `int` anytime that want. (: 

I would prefer not merging it, there is little value here. What do you think? 🤗

2021-07-24 18:29 UTC, kuritka commented
@bwplotka, thanks for the review although it is rejected. In a way, you're right, but everyone will now have to implement this simple minor feature themselves. A bit of usefulness is the only reason to put it in the utilities, regardless of the small amount of code it contains. 

The change is not crucial for me, so I'll leave it as it is. 

Thx and good luck

2021-07-24 19:31 UTC, bwplotka commented
Thanks!

It's better to minimize the stuff we ship to thousand people to bare high quality minimum. Simpler = better.

You can always have quick local function in your project.

While we are here I would definitely change method name.. toFloat is not super helpful 🙈

2021-07-24 19:31 UTC, closed without merging